export const hazardInformation = {
  HEALTH_HAZARD: {
    0: "Normal material",
    1: "Slightly hazardous",
    2: "Hazardous",
    3: "Extreme danger",
    4: "Deadly",
  },
  FIRE_HAZARD: {
    0: "Will not burn",
    1: "Above 93° C",
    2: "Below 93° C",
    3: "Below 38° C",
    4: "Below 23° C",
  },
  SPECIFIC_HAZARD: [
    "Oxidizer",
    "Acid",
    "ACID",
    "Alkali",
    "ALK",
    "Corrosive",
    "COR",
    "Use NO WATER",
    "W",
    "Radiation Hazard",
  ],
  INSTABILITY: {
    0: "Stable",
    1: "Unstable if heated",
    2: "Violent chemical change",
    3: "Shock and heat may detonate",
    4: "May detonate",
  },
};

export const chemicals = {
  UN1005: {
    Name: "Ammonia, anhydrous",
    NEEDMONITOR: true,
    TLV_TWA: [{ NIOSH: "35 mg/m³" }, { OSHA: "50 ppm" }],
    INSTABILITY: 1,
    SPECIFIC_HAZARD: "Corrosive",
    FIRE_HAZARD: 1,
    HEALTH_HAZARD: 3,
    STATE: "Gas",
    OXIDIZER: false,
    CORROSIVE: true,
    FLAMMABLE: true,
    PPE: ["gloves", "goggles", "respirator"],
  },
  UN1017: {
    Name: "Chlorine",
    NEEDMONITOR: false,
    TLV_TWA: [],
    INSTABILITY: 0,
    SPECIFIC_HAZARD: "Oxidizer",
    FIRE_HAZARD: 0,
    HEALTH_HAZARD: 3,
    STATE: "Gas",
    OXIDIZER: true,
    CORROSIVE: true,
    FLAMMABLE: false,
    PPE: ["gloves", "goggles", "respirator", "protective suit"],
  },
  UN1090: {
    Name: "Acetone",
    NEEDMONITOR: false,
    TLV_TWA: [],
    INSTABILITY: 1,
    SPECIFIC_HAZARD: "None",
    FIRE_HAZARD: 3,
    HEALTH_HAZARD: 1,
    STATE: "Liquid",
    OXIDIZER: false,
    CORROSIVE: false,
    FLAMMABLE: true,
    PPE: ["gloves", "goggles"],
  },
  UN1202: {
    Name: "Diesel fuel",
    NEEDMONITOR: false,
    TLV_TWA: [],
    INSTABILITY: 0,
    SPECIFIC_HAZARD: "None",
    FIRE_HAZARD: 2,
    HEALTH_HAZARD: 2,
    STATE: "Liquid",
    OXIDIZER: false,
    CORROSIVE: false,
    FLAMMABLE: true,
    PPE: ["gloves", "goggles"],
  },
  UN1588: {
    Name: "Toxic Substance",
    NEEDMONITOR: true,
    TLV_TWA: [{ NIOSH: "TWA varies" }, { OSHA: "PEL varies" }],
    INSTABILITY: 0,
    SPECIFIC_HAZARD: "TOX",
    FIRE_HAZARD: 0,
    HEALTH_HAZARD: 3,
    STATE: "Solid",
    OXIDIZER: true,
    CORROSIVE: false,
    FLAMMABLE: true,
    PPE: ["gloves", "goggles", "respirator", "protective suit"],
  },
  UN1824: {
    Name: "Sodium hydroxide solution",
    NEEDMONITOR: false,
    TLV_TWA: [],
    INSTABILITY: 0,
    SPECIFIC_HAZARD: "Corrosive",
    FIRE_HAZARD: 0,
    HEALTH_HAZARD: 3,
    STATE: "Liquid",
    OXIDIZER: false,
    CORROSIVE: true,
    FLAMMABLE: false,
    PPE: ["gloves", "goggles", "face shield", "protective suit"],
  },
  UN0029: {
    Name: "Explosive Material",
    NEEDMONITOR: false,
    TLV_TWA: [],
    INSTABILITY: 4,
    SPECIFIC_HAZARD: "None",
    FIRE_HAZARD: 0,
    HEALTH_HAZARD: 0,
    STATE: "Solid",
    OXIDIZER: false,
    CORROSIVE: false,
    FLAMMABLE: true,
    PPE: ["gloves", "goggles", "face shield"],
  },
  UN1040: {
    Name: "Ethylene oxide",
    NEEDMONITOR: false,
    TLV_TWA: [],
    INSTABILITY: 2,
    SPECIFIC_HAZARD: "Explosive",
    FIRE_HAZARD: 4,
    HEALTH_HAZARD: 3,
    STATE: "Gas",
    OXIDIZER: false,
    CORROSIVE: false,
    FLAMMABLE: true,
    PPE: ["gloves", "goggles"],
  },
  UN1075: {
    Name: "Propane",
    NEEDMONITOR: true,
    TLV_TWA: [{ NIOSH: "1800 mg/m³" }, { OSHA: "1000 ppm" }],
    INSTABILITY: 0,
    SPECIFIC_HAZARD: "None",
    FIRE_HAZARD: 3,
    HEALTH_HAZARD: 0,
    STATE: "Gas",
    OXIDIZER: false,
    CORROSIVE: false,
    FLAMMABLE: true,
    PPE: ["gloves", "goggles"],
  },
  UN1170: {
    Name: "Ethanol",
    NEEDMONITOR: false,
    TLV_TWA: [],
    INSTABILITY: 0,
    SPECIFIC_HAZARD: "None",
    FIRE_HAZARD: 3,
    HEALTH_HAZARD: 2,
    STATE: "Liquid",
    OXIDIZER: false,
    CORROSIVE: false,
    FLAMMABLE: true,
    PPE: ["gloves", "goggles", "respirator"],
  },
  UN1203: {
    Name: "Gasoline",
    NEEDMONITOR: true,
    TLV_TWA: [{ NIOSH: "300 ppm" }, { OSHA: "900 mg/m³" }],
    INSTABILITY: 0,
    SPECIFIC_HAZARD: "None",
    FIRE_HAZARD: 3,
    HEALTH_HAZARD: 0,
    STATE: "Liquid",
    OXIDIZER: false,
    CORROSIVE: false,
    FLAMMABLE: true,
    PPE: ["gloves", "goggles", "face shield"],
  },
  UN1219: {
    Name: "Isopropanol",
    NEEDMONITOR: false,
    TLV_TWA: [],
    INSTABILITY: 0,
    SPECIFIC_HAZARD: "None",
    FIRE_HAZARD: 3,
    HEALTH_HAZARD: 2,
    STATE: "Liquid",
    OXIDIZER: false,
    CORROSIVE: false,
    FLAMMABLE: true,
    PPE: ["gloves", "goggles", "respirator"],
  },
  UN1230: {
    Name: "Methanol",
    NEEDMONITOR: true,
    TLV_TWA: [{ NIOSH: "260 mg/m³" }, { OSHA: "200 ppm" }],
    INSTABILITY: 0,
    SPECIFIC_HAZARD: "POI",
    FIRE_HAZARD: 3,
    HEALTH_HAZARD: 4,
    STATE: "Liquid", // Methanol is a liquid at room temperature, not gas.
    OXIDIZER: false,
    CORROSIVE: false,
    FLAMMABLE: true,
    PPE: ["gloves", "goggles", "respirator", "protective suit"],
  },
  UN1344: {
    Name: "Ferrous Sulfide",
    NEEDMONITOR: false,
    TLV_TWA: [],
    INSTABILITY: 0,
    SPECIFIC_HAZARD: "None",
    FIRE_HAZARD: 2,
    HEALTH_HAZARD: 0,
    STATE: "Solid",
    OXIDIZER: true,
    CORROSIVE: false,
    FLAMMABLE: true,
    PPE: ["gloves", "goggles"],
  },
  UN1748: {
    Name: "Oxidizing Substance",
    NEEDMONITOR: false,
    TLV_TWA: [],
    INSTABILITY: 2,
    SPECIFIC_HAZARD: "OXI",
    FIRE_HAZARD: 2,
    HEALTH_HAZARD: 0,
    STATE: "Solid",
    OXIDIZER: true,
    CORROSIVE: false,
    FLAMMABLE: false,
    PPE: ["gloves", "goggles", "face shield"],
  },
};
export default hazardInformation;
